version: 2

models:
  - name: dim_accounts
    description: "Account-level view combining contacts, engagement, and pipeline outcomes."
    columns:
      - name: contact_id
        description: "Primary key for the account/contact record."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_hubspot_contacts')
              field: contact_id
      - name: first_name
        description: "Contact first name."
      - name: last_name
        description: "Contact last name."
      - name: restaurant_name
        description: "Restaurant or company name tied to the account."
      - name: contact_created_at
        description: "Timestamp when the source contact was created."
      - name: total_web_visits
        description: "Total number of tracked website visits for the contact."
      - name: total_opportunities
        description: "Count of all opportunities associated with the contact."
      - name: total_arr_generated
        description: "Total ARR from closed-won opportunities for the contact."
      - name: current_pipeline_stage
        description: "Latest known opportunity stage based on opportunity timestamps."

  - name: fct_revenue_attribution
    description: "Opportunity-level fact table attributing closed-won ARR to first-touch marketing channel."
    columns:
      - name: opportunity_id
        description: "Primary key for closed-won opportunities in the attribution model."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_sfdc_opportunities')
              field: opportunity_id
      - name: contact_id
        description: "Contact associated with the opportunity."
        tests:
          - relationships:
              to: ref('stg_hubspot_contacts')
              field: contact_id
      - name: restaurant_name
        description: "Restaurant or company tied to the attributed opportunity."
      - name: arr_amount
        description: "Attributed ARR amount from the opportunity."
      - name: acquiring_channel
        description: "First-touch marketing channel for the contact."
      - name: opp_closed_at
        description: "Opportunity close timestamp."
