version: 2

models:
  - name: dim_accounts
    description: "Account-level view combining contacts, engagement, and pipeline outcomes."
    columns:
      - name: contact_id
        description: "Primary key for the account/contact record."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_hubspot_contacts')
              field: contact_id
      - name: first_name
        description: "Contact first name."
      - name: last_name
        description: "Contact last name."
      - name: company_name
        description: "Company name tied to the account."
        tests:
          - not_null
      - name: contact_created_at
        description: "Timestamp when the source contact was created."
        tests:
          - not_null
      - name: total_web_visits
        description: "Total number of tracked website visits for the contact."
        tests:
          - not_null
      - name: total_opportunities
        description: "Count of all opportunities associated with the contact."
        tests:
          - not_null
      - name: total_arr_generated
        description: "Total ARR from closed-won opportunities for the contact."
        tests:
          - not_null
      - name: current_pipeline_stage
        description: "Latest known opportunity stage based on opportunity timestamps."
        tests:
          # If a contact has no opportunities, they might not have a stage, but if they do, it must be valid.
          - accepted_values:
              values: ['Prospecting', 'Qualification', 'Pilot Program', 'Closed Won', 'Closed Lost']
      - name: dbt_updated_at
        description: "Audit timestamp capturing exactly when this row was generated by dbt."
        tests:
          - not_null
      - name: dbt_run_id
        description: "The unique dbt invocation ID used to trace this row back to a specific pipeline run."
        tests:
          - not_null

  - name: fct_revenue_attribution
    description: "Opportunity-level fact table attributing closed-won ARR to first-touch marketing channel."
    columns:
      - name: opportunity_id
        description: "Primary key for closed-won opportunities in the attribution model."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_sfdc_opportunities')
              field: opportunity_id
      - name: contact_id
        description: "Contact associated with the opportunity."
        tests:
          - not_null
          - relationships:
              to: ref('stg_hubspot_contacts')
              field: contact_id
      - name: company_name
        description: "Restaurant or company tied to the attributed opportunity."
        tests:
          - not_null
      - name: arr_amount
        description: "Attributed ARR amount from the opportunity."
        tests:
          - not_null
      - name: acquiring_channel
        description: "First-touch marketing channel for the contact."
        tests:
          - not_null
          - accepted_values:
              values: ['LinkedIn B2B', 'Local Chamber of Commerce', 'Google Ads (Eco)', 'Direct', 'Partner Referral']
      - name: opp_closed_at
        description: "Opportunity close timestamp."
        tests:
          - not_null # Crucial validation!
      - name: dbt_updated_at
        description: "Audit timestamp capturing exactly when this row was generated by dbt."
        tests:
          - not_null
      - name: dbt_run_id
        description: "The unique dbt invocation ID used to trace this row back to a specific pipeline run."
        tests:
          - not_null