name: 'gtm_project'
version: '1.0.0'
config-version: 2

profile: 'gtm_project'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gtm_project:
    # Staging models will be created as views
    staging:
      +materialized: view
      +schema: staging
    # Mart models (business logic) will be created as physical tables
    marts:
      +materialized: table